#!/usr/bin/env python3
"""md2html: 把 markdown 文件转成带样式的 HTML。

用法:
    python3 md2html.py <input.md>           # 输出到同目录的 input.html
    python3 md2html.py <input.md> -o out.html

依赖:
    pip3 install markdown

样式由本目录下的 style.css 控制(内联进 HTML,生成的文件可独立打开)。
"""

import argparse
import sys
from pathlib import Path

try:
    import markdown
except ImportError:
    print("缺少 markdown 库,请先安装: pip3 install markdown", file=sys.stderr)
    sys.exit(1)


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
{css}
</style>
</head>
<body>
<main class="container">
{body}
<div class="footer">{footer}</div>
</main>
</body>
</html>
"""


def convert(md_path: Path, out_path: Path, css_path: Path) -> None:
    """读 md → 转 html → 套 css → 写文件."""
    md_text = md_path.read_text(encoding="utf-8")

    # 提取一级标题作为 <title>,fallback 用文件名
    title = md_path.stem
    for line in md_text.splitlines():
        line = line.strip()
        if line.startswith("# "):
            title = line[2:].strip()
            break

    # markdown 转换 — 启用常用扩展:表格 / 围栏代码 / 任务列表 / 目录 / 锚点
    extensions = [
        "extra",        # 表格 / 围栏代码 / def list 等
        "sane_lists",
        "toc",
        "tables",
        "fenced_code",
    ]
    extension_configs = {"toc": {"permalink": False}}

    # tasklist 来自 pymdown-extensions,装了就启用,没装也能跑
    try:
        import pymdownx.tasklist  # noqa: F401
        extensions.append("pymdownx.tasklist")
        extension_configs["pymdownx.tasklist"] = {"custom_checkbox": False}
    except ImportError:
        pass

    body_html = markdown.markdown(
        md_text,
        extensions=extensions,
        extension_configs=extension_configs,
    )

    # 读 css
    if css_path.exists():
        css = css_path.read_text(encoding="utf-8")
    else:
        css = "/* style.css 未找到,使用裸样式 */"

    footer = f"{title} · generated by plan-report skill"

    html = HTML_TEMPLATE.format(title=title, css=css, body=body_html, footer=footer)
    out_path.write_text(html, encoding="utf-8")
    print(f"已生成: {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="markdown → html 转换工具(带 plan-report 默认样式)")
    parser.add_argument("input", help="输入的 markdown 文件路径")
    parser.add_argument("-o", "--output", help="输出 html 路径,默认为同目录同名 .html")
    parser.add_argument(
        "--css",
        help="自定义 CSS 文件路径,默认使用本 skill 目录的 style.css",
    )
    args = parser.parse_args()

    md_path = Path(args.input).resolve()
    if not md_path.exists():
        print(f"找不到输入文件: {md_path}", file=sys.stderr)
        sys.exit(1)

    out_path = Path(args.output).resolve() if args.output else md_path.with_suffix(".html")
    css_path = Path(args.css).resolve() if args.css else Path(__file__).parent / "style.css"

    convert(md_path, out_path, css_path)


if __name__ == "__main__":
    main()
